---
- name: deploy app
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      notify: reload puma

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
